# Generated by Django 6.0.1 on 2026-01-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('full_path', models.CharField(max_length=1000)),
                ('headers', models.JSONField()),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('body_raw', models.TextField(blank=True, null=True)),
                ('body_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('login_email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_complement', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('operating_hour_start', models.TimeField(blank=True, null=True)),
                ('operating_hour_end', models.TimeField(blank=True, null=True)),
                ('extraFields', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
