# Generated by Django 6.0.2 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
