# Generated by Django 6.0.2 on 2026-03-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptor', '0002_customer_cep_alter_customer_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='dadosclientes',
        ),
    ]
