# Generated by Django 6.0.2 on 2026-03-17 18:30

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('receptor', '0003_alter_customer_table'),  # mantenha o que já está
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE dados_entrega ADD COLUMN IF NOT EXISTS cd_filial varchar(10);",
            reverse_sql="ALTER TABLE dados_entrega DROP COLUMN IF EXISTS cd_filial;",
        ),
    ]