# Generated by Django 6.0.2 on 2026-03-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptor', '0003_alter_customer_table'),
    ]

    """operations = [
        migrations.AlterModelTable(
            name='customer',
            table='dadosclientes',
        ),
]"""
