# Generated by Django 6.0.2 on 2026-04-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptor', '0004_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='dadosclientes',
        ),
    ]
