# Generated by Django 6.0.1 on 2026-02-11 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_entr', models.IntegerField()),
                ('cd_vd', models.IntegerField()),
                ('cd_fun_entr', models.IntegerField(blank=True, null=True)),
                ('cd_fun_lib', models.IntegerField(blank=True, null=True)),
                ('cd_mov_ret', models.IntegerField(blank=True, null=True)),
                ('data_entr_ini', models.DateField(auto_now_add=True)),
                ('hora_entr_ini', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dados_entrega',
            },
        ),
        migrations.CreateModel(
            name='DadosVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_cli', models.IntegerField()),
                ('cd_nf', models.IntegerField()),
                ('cd_vd', models.IntegerField()),
            ],
            options={
                'db_table': 'dados_venda',
                'unique_together': {('cd_nf', 'cd_vd')},
            },
        ),
        migrations.CreateModel(
            name='EntregaFinalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.IntegerField(blank=True, null=True)),
                ('cupomfiscal', models.IntegerField(blank=True, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_hora_entrega', models.DateTimeField(auto_now_add=True)),
                ('entrega_status', models.CharField(choices=[('ENTREGUE', 'Entregue'), ('CLIENTE_AUSENTE', 'Cliente ausente'), ('ENDERECO_INCORRETO', 'Endereço incorreto'), ('CLIENTE_RECUSOU', 'Cliente recusou')], default='ENTREGUE', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptor.customer')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_finalizadas', to='software.dadosentrega')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_finalizadas', to='software.dadosvenda')),
            ],
            options={
                'db_table': 'entrega_finalizada',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios_lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_usu', models.IntegerField(blank=True, help_text='Código legado do vetor', null=True, unique=True)),
                ('funcao', models.CharField(choices=[('ENTREGADOR', 'Entregador'), ('OP. DE CAIXA', 'Op. de Caixa'), ('GERENTE', 'Gerente'), ('ADMINISTRATIVO', 'Administrativo'), ('S. GERENTE', 'S. Gerente')], default='DEFINIR', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'glb_usu',
            },
        ),
    ]
