# Generated by Django 6.0.2 on 2026-03-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptor', '0004_alter_customer_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_entr', models.IntegerField()),
                ('cd_vd', models.IntegerField()),
                ('cd_fun_entr', models.IntegerField(blank=True, null=True)),
                ('cd_fun_lib', models.IntegerField(blank=True, null=True)),
                ('cd_mov_ret', models.IntegerField(blank=True, null=True)),
                ('cd_filial', models.IntegerField(blank=True, null=True)),
                ('data_entr_ini', models.DateField(auto_now_add=True)),
                ('hora_entr_ini', models.TimeField(auto_now_add=True)),
                ('data_hora_atribuicao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dados_entrega',
                'unique_together': {('cd_entr', 'cd_vd', 'cd_filial')},
            },
        ),
        migrations.CreateModel(
            name='dadoskilometragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_diario', models.FloatField(default=0.0)),
                ('data_apuracao', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usermotoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacao_motoboy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_diario',
            },
        ),
        migrations.CreateModel(
            name='DadosVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_cli', models.IntegerField()),
                ('cd_nf', models.IntegerField()),
                ('cd_vd', models.IntegerField()),
            ],
            options={
                'db_table': 'dados_venda',
                'unique_together': {('cd_nf', 'cd_vd')},
            },
        ),
        migrations.CreateModel(
            name='EntregaFinalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.IntegerField(blank=True, null=True)),
                ('cupomfiscal', models.IntegerField(blank=True, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_hora_entrega', models.DateTimeField(auto_now_add=True)),
                ('entrega_status', models.CharField(choices=[('ENTREGUE', 'Entregue'), ('CLIENTE_AUSENTE', 'Cliente ausente'), ('ENDERECO_INCORRETO', 'Endereço incorreto'), ('CLIENTE_RECUSOU', 'Cliente recusou')], default='ENTREGUE', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptor.customer')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_finalizadas', to='software.dadosentrega')),
                ('usermotoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.dadosvenda')),
            ],
            options={
                'db_table': 'entrega_finalizada',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios_lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_usu', models.IntegerField(blank=True, help_text='Código legado do vetor', null=True, unique=True)),
                ('funcao', models.CharField(choices=[('DEFINIR', 'Definir'), ('ENTREGADOR', 'Entregador'), ('OP. DE CAIXA', 'Op. de Caixa'), ('GERENTE', 'Gerente'), ('ADMINISTRATIVO', 'Administrativo'), ('S. GERENTE', 'S. Gerente')], default='DEFINIR', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'glb_usu',
            },
        ),
        migrations.CreateModel(
            name='HistoricoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Entrega',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
