# Generated by Django 6.0.1 on 2026-01-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('full_path', models.CharField(max_length=1000)),
                ('headers', models.JSONField()),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('body_raw', models.TextField(blank=True, null=True)),
                ('body_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'receptor_apirequest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('c_type', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('login_email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_complement', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('operating_hour_start', models.TimeField(blank=True, null=True)),
                ('operating_hour_end', models.TimeField(blank=True, null=True)),
                ('extraFields', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receptor_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DadosEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_entr', models.IntegerField()),
                ('cd_vd', models.IntegerField()),
                ('cd_fun_entr', models.IntegerField(blank=True, null=True)),
                ('cd_fun_lib', models.IntegerField(blank=True, null=True)),
                ('cd_mov_ret', models.IntegerField(blank=True, null=True)),
                ('data_entr_ini', models.DateField(auto_now_add=True)),
                ('hora_entr_ini', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dados_entrega',
            },
        ),
        migrations.CreateModel(
            name='Funcionarios_lista',
            fields=[
                ('cd_usu', models.AutoField(primary_key=True, serialize=False)),
                ('nm_usu', models.CharField(max_length=100)),
                ('ds_senha', models.CharField(default='123456', max_length=100)),
                ('funcao', models.CharField(choices=[('ENTREGADOR', 'Entregador'), ('OP. DE CAIXA', 'Op. de Caixa'), ('GERENTE', 'Gerente'), ('ADMINISTRATIVO', 'Adminstrativo'), ('S. GERENTE', 'S. Gerente'), ('DEFINIR', 'DEFINIR')], default='DEFINIR', max_length=50)),
            ],
            options={
                'db_table': 'glb_usu',
            },
        ),
        migrations.CreateModel(
            name='DadosVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_cli', models.IntegerField()),
                ('cd_nf', models.IntegerField()),
                ('cd_vd', models.IntegerField()),
            ],
            options={
                'db_table': 'dados_venda',
                'unique_together': {('cd_nf', 'cd_vd')},
            },
        ),
        migrations.CreateModel(
            name='EntregaFinalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.IntegerField(blank=True, null=True)),
                ('nome_cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(blank=True, max_length=300, null=True)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('data_hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_hora_entrega', models.DateTimeField(auto_now_add=True)),
                ('entrega_status', models.CharField(choices=[('ENTREGUE', 'Entregue'), ('CLIENTE_AUSENTE', 'Cliente ausente'), ('ENDERECO_INCORRETO', 'Endereço incorreto'), ('CLIENTE_RECUSOU', 'Cliente recusou')], default='ENTREGUE', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.customer')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_finalizadas', to='software.dadosentrega')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_finalizadas', to='software.dadosvenda')),
            ],
            options={
                'db_table': 'entrega_finalizada',
            },
        ),
    ]
