# Generated by Django 6.0.2 on 2026-03-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadosentrega',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='dadosentrega',
            name='data_hora_atribuicao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
