# Generated by Django 6.0.2 on 2026-03-06 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregafinalizada',
            name='usermotoboy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_finalizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='dadoskilometragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_diario', models.FloatField(default=0.0)),
                ('data_apuracao', models.DateField(blank=True, null=True)),
                ('usermotoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacao_motoboy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'km_diario',
            },
        ),
    ]
