# Generated by Django 6.0.1 on 2026-01-28 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptor', '0001_initial'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiRequest',
        ),
        migrations.AlterField(
            model_name='entregafinalizada',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receptor.customer'),
        ),
        migrations.AddField(
            model_name='entregafinalizada',
            name='cupomfiscal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
