# Generated by Django 6.0.2 on 2026-04-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_dadosentrega_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregafinalizada',
            options={'ordering': ['-data_hora_entrega']},
        ),
        migrations.CreateModel(
            name='EscalaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_fixo_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], help_text='Dia que o funcionário sempre folga')),
                ('domingo_do_mes', models.IntegerField(choices=[(1, '1º Domingo do Mês'), (2, '2º Domingo do Mês'), (3, '3º Domingo do Mês'), (4, '4º Domingo do Mês')], help_text='Qual domingo do mês ele folga')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escala_fixa', to='software.funcionarios_lista')),
            ],
            options={
                'db_table': 'folgasfixas',
            },
        ),
    ]
