# Generated by Django 6.0.2 on 2026-03-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_dadoskilometragem_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoskilometragem',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
