# Generated by Django 6.0.2 on 2026-03-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_alter_dadoskilometragem_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios_lista',
            name='funcao',
            field=models.CharField(choices=[('DEFINIR', 'Definir'), ('ENTREGADOR', 'Entregador'), ('OP. DE CAIXA', 'Op. de Caixa'), ('GERENTE', 'Gerente'), ('ADMINISTRATIVO', 'Administrativo'), ('S. GERENTE', 'S. Gerente')], default='DEFINIR', max_length=50),
        ),
    ]
