# Generated by Django 6.0.2 on 2026-04-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_forum_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalafixa',
            name='tipo_escala',
            field=models.CharField(choices=[('FIXO', 'Folga Fixa'), ('SAB_DOM_ALT', 'Sábado e Domingo Alternados'), ('DIÁRIA', 'Diária'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='FIXO', help_text='Tipo de escala fixa', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionarios_lista',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='escalafixa',
            name='domingo_do_mes',
            field=models.IntegerField(blank=True, choices=[(1, '1º Domingo do Mês'), (2, '2º Domingo do Mês'), (3, '3º Domingo do Mês'), (4, '4º Domingo do Mês')], help_text='Qual domingo do mês ele folga', null=True),
        ),
    ]
