# Generated by Django 6.0.2 on 2026-03-11 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_alter_entregafinalizada_venda_historicoentrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricoEntrega',
            new_name='HistoricoLocalizacao',
        ),
    ]
