# Generated by Django 6.0.2 on 2026-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0006_filial_funcionarios_lista_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoskilometragem',
            name='gorjeta',
            field=models.FloatField(default=0.0),
        ),
    ]
