# Generated by Django 6.0.2 on 2026-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_rename_historicoentrega_historicolocalizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicolocalizacao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Histórico de Entrega'},
        ),
        migrations.AlterField(
            model_name='historicolocalizacao',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='historicolocalizacao',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
