# Generated by Django 6.0.1 on 2026-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_dadoskilometragem_gorjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregafinalizada',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='entregafinalizada',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
