# Generated by Django 6.0.2 on 2026-04-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_dadoskilometragem_gorjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalafixa',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data de início da escala alternada', null=True),
        ),
    ]
