# Generated by Django 6.0.2 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_alter_historicolocalizacao_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE dados_entrega ADD COLUMN IF NOT EXISTS cd_filial integer;",
            reverse_sql="ALTER TABLE dados_entrega DROP COLUMN IF EXISTS cd_filial;",
        ),
        migrations.AlterUniqueTogether(
            name='dadosentrega',
            unique_together={('cd_entr', 'cd_vd')},
        ),
    ]