# Generated by Django 6.0.2 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0008_alter_historicolocalizacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosentrega',
            name='cd_filial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dadosentrega',
            unique_together={('cd_entr', 'cd_vd')},
        ),
    ]
